FROM node:16-alpine

# Env
ENV NODE_ENV dev

EXPOSE 8005

WORKDIR /app
COPY package*.json ./
COPY prisma ./
RUN npm install
COPY . /app
ENTRYPOINT ["/bin/sh", "-c" , "npm run migrate:deploy && npx prisma generate && npm run start:dev"]